### ISSUE TITLE
Some more todo items

### ISSUE THREAD

**Issue by jimexist** [Tianqi0616/Madadata_project#2]
- [x] remove the TodoMVC code and change the default styles
- [x] make sure there's no error or warnings in `console`
- [x] make sure it (and d3) runs under Chrome and Safari
- [ ] use webpack to pack all `.js` files, so that you can have modular code base, and also you can use `npm` to install dependencies like react - instead of requiring them in `html` file, you can require the webpack processed bundle in one `<script>` tag

**Comment by Tianqi0616** [comment]
Console 应该是没有errors了，我回头再解决warnings的问题。

**Comment by Tianqi0616** [comment]
Chrome显示问题解决了，不是浏览器的问题，是CSS里tag的attribute没有设置好

**Comment by Tianqi0616** [comment]
我用webpack pack了一个bundle2.js想用来代替utils.js和screener.js，但是在html里require了bundle2.js之后发现似乎没有成功代替那两个js文件，想知道我到底是哪一步出错了呢？我生成的bundle2.js已经push到github上了，以及用来生成bundle的wepack.config.js。
